on:
  push:
    branches:
      dev

name: Run Flutter Tests
job:
  flutter-tests:
    name: "Run tests"
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.24.3
      - name: Install Dependencies
        run: flutter pub get
      - name: Test project
        run: flutter test